from . import hr_hospital_person_mixin
from . import hr_hospital_doctor
from . import hr_hospital_contact_person
from . import hr_hospital_patient
from . import hr_hospital_patient_study
from . import hr_hospital_disease_type
from . import hr_hospital_sample_type
from . import hr_hospital_study_type
from . import hr_hospital_disease
from . import hr_hospital_diagnosis
from . import hr_hospital_visit
from . import hr_hospital_personal_doctor_history
